title: "Remote theme example"
remote_theme: pmarsceill/just-the-docs
description: A Jekyll theme for documentation
# baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog
# url: "https://payroad-guide.github.io" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: "dark"
search_enabled: true

